import React from "react";
import type {Metadata} from "next";

import "./globals.css";

import "@mantine/core/styles.css";
import {ColorSchemeScript, MantineProvider} from "@mantine/core";

export const metadata: Metadata = {
  title: "Attendance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <ColorSchemeScript/>
      <title>{`${metadata.title}`}</title>
    </head>
    <body>
    <MantineProvider>{children}</MantineProvider>
    </body>
    </html>
  );
}
